name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: mcr.microsoft.com/windows/servercore:ltsc2016

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag edgehog/windows/servercore/ltsc2016/chocolatey
